[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "autoir"
version = "2026.04.18"
description = "AutoIR"
authors = [{name = "Daniel Schwalbe-Koda", email = "dskoda@ucla.edu"}]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
keywords = ["feed", "reader", "tutorial"]
dependencies = [
    "numpy",
    "pandas",
    "click",
    "jinja2",
    "scipy",
    "openff-toolkit",
]

[project.scripts]
autoir = "autoir.cli.main:autoir"

[tool.setuptools]
packages = ["autoir"]
